### ISSUE TITLE
Looking for an elegant way to include all generated files.

### ISSUE THREAD

**Issue by Flone-dnb** [jsoysouvanh/Refureku#14]
Hi once again.

I'm implementing a serializer/deserializer for custom user types. My idea is to have a base class `Serializable` (reflected class that derives from `rfk::Object`) and allow users to create new classes that inherit from this `Serializable` class to enable serialization/deserialization. The problem I stumbled upon is that if I don't include a specific generated implementation file (`rfks.h`) the database will not know this class' ID. Because my `serialize`/`deserialize` functions are located in the base class `Serializable` when reading a class ID from the file to deserialize it I need to have information about the specific class that this class ID represents.

So I'm asking if maybe you also had this problem and know an elegant way to include all generated information in the base class so that it will know about all class IDs (and can work with all reflected types).

The only solution I come up with is to dynamically create (using a pre build script) a `Reflection.h` and `Reflection.cpp` files that include all generated files and use (include) them (`Reflection.h` and `Reflection.cpp`) everywhere in the code instead of including actually generated files. But this is not really a good solution because once you make a change in just one class that uses reflection all other classes that use reflection are also being recompiled (which takes quite some time). All of my other attempts to solve this lead to `[LNK1169] one or more multiply defined symbols found`.

**Comment by jsoysouvanh** [comment]
The only requirement for the database to be up-to-date with all reflected types is that each .rfks.h must be included once and only once in the final executable.
Why is including generated files (.rfks.h) a problem? Not including the file means the generated code will not be part of the final executable (so the class won't be registered).

If you are using CMake, you can maybe add all generated files to the list of files in the executable target using a GLOB expression. If you do so, you do not have to (and must not) include the .rfks.h files manually anymore in your program.

**Comment by Flone-dnb** [comment]
> each .rfks.h must be included once and only once in the final executable

Oh I'm stupid, even the linker was telling me what is wrong, I guess I'm just tired for today . I've realized what I was doing wrong.
Really sorry for bothering you. 😄
