### ISSUE TITLE
Weird full paths in generated code

### ISSUE THREAD

**Issue by exuvo** [jsoysouvanh/Refureku#16]
I do not understand what i did for this to start happening. Has worked fine for months. Was making an unrelated change and suddenly it stopped building due to this and even reverting to yesterdays codebase does not compile anymore.

I have a header with this and some more:
```
includes...

struct RFKStruct(kodgen::ParseAllNested) MovementValues {
		Vector2l position;     // m
		Vector2l velocity;     // cm/s
		Vector2l acceleration; // cm/s²
		
		MovementValues() {
			position = {0, 0};
			velocity = {0, 0};
			acceleration = {0, 0};
		}
		
		MovementValues(Vector2l position2, Vector2l velocity2, Vector2l acceleration2) {
			position = position2;
			velocity = velocity2;
			acceleration = acceleration2;
		}
		
		MovementValues(uint32_t x, uint32_t y, uint32_t vx, uint32_t vy, uint32_t ax, uint32_t ay) {
			position = {x, y};
			velocity = {vx, vy};
			acceleration = {ax, ay};
		}
		
		Vector2l getPositionInKM() {
			return Vector2l { (signum(position.x()) * 500 + position.x()) / 1000, (signum(position.y()) * 500 + position.y()) / 1000};
		}
		
		MovementValues_GENERATED
};

template<typename T>
struct RFKStruct(kodgen::ParseAllNested) TimedValue {
		T value;
		uint64_t time;
		
		TimedValue_GENERATED
};

template<typename T>
struct RFKStruct(kodgen::ParseAllNested) TimedComponent {
		virtual TimedValue<T> get(uint64_t time) = 0;
		
		virtual ~TimedComponent() = default;
		
		TimedComponent_GENERATED
};

more code...
```
which used to work fine, that code is not touched recently.
But the generated output for this file now contains full paths for typenames.

```
#define MovementValues_GENERATED	\
...
#define __home_exuvo_code_Aurora_C_src_starsystems_components_TimedComponents_hpp_TimedValue_GENERATED	\
...
#define __home_exuvo_code_Aurora_C_src_starsystems_components_TimedComponents_hpp_TimedComponent_GENERATED	\
...
```
```
#define File_TimedComponents_GENERATED	\
template <>  rfk::Archetype const* rfk::getArchetype<MovementValues>() noexcept;\
template <>  rfk::Archetype const* rfk::getArchetype<::/home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp::TimedValue>() noexcept;\
template <>  rfk::Archetype const* rfk::getArchetype<::/home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp::TimedComponent>() noexcept;\
template <>  rfk::Archetype const* rfk::getArchetype<::/home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp::InterpolatedComponent>() noexcept;\
template <>  rfk::Archetype const* rfk::getArchetype<TimedMovementComponent>() noexcept;\
```
which is obviously giving me expression errors as that is not a valid typename.
Any clue what is happening? I have not done any system updates since yesterday (or earlier today) when it last worked.
I have tried a computer reboot in case it was a corrupt file cache problem but no luck there.

The only common thing i can see is that those 3 all use templates but that has only been a minor problem in the past with a warning on startup about multiple registrations.

Refureku log is not showing anything unusual:
```
[Info] Working Directory: /home/exuvo/code/Aurora-C
[Info] [TOML] Load cppVersion: c++20
[Info] [TOML] Load shouldParseAllNamespaces: false
[Info] [TOML] Load shouldParseAllClasses: false
[Info] [TOML] Load shouldParseAllStructs: false
[Info] [TOML] Load shouldParseAllVariables: false
[Info] [TOML] Load shouldParseAllFields: false
[Info] [TOML] Load shouldParseAllFunctions: false
[Info] [TOML] Load shouldParseAllMethods: false
[Info] [TOML] Load shouldParseAllEnums: false
[Info] [TOML] Load shouldParseAllEnumValues: true
[Info] [TOML] Load shouldAbortParsingOnFirstError: true
[Info] [TOML] Load shouldLogDiagnostic: false
[Info] [TOML] Load compiler: g++
[Info] [TOML] Load new project include directory: /usr/include/apr-1
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/Refureku/Refureku/Library/Include/Public
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/src
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/asmlib
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/tlsf
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/tracy
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/soloud/include
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/stb
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/SLikeNet/Source/include
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/mimalloc/include
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/entt/src
[Info] [TOML] Load new project include directory: /usr/include/freetype2
[Info] [TOML] Load new project include directory: /usr/include
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/imgui_sugar
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/tracy/client
[Info] [TOML] Load new project include directory: /home/exuvo/code/Aurora-C/lib/tracy/common
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/utils/Math.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/StrategicIconComponent.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/CargoComponent.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/ColonyComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/HealthComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/Components.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/SimpleComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/IDComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/PartStatesComponent.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/PowerComponent.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/MiscComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/MovementComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/SensorComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/MunitionComponents.hpp
[Info] [TOML] Load new file to parse: /home/exuvo/code/Aurora-C/src/starsystems/components/ShipComponent.hpp
[Info] [TOML] Load new ignored directory: /home/exuvo/code/Aurora-C/src/refureku
[Info] [TOML] Load output directory: /home/exuvo/code/Aurora-C/src/refureku
[Info] [TOML] Load generated header file name pattern: ##FILENAME##.rfkh.h
[Info] [TOML] Load generated source file name pattern: ##FILENAME##.rfks.h
[Info] [TOML] Load class footer macro pattern: ##FILENAME##.rfkh.h
[Info] [TOML] Load header file footer macro pattern: ##FILENAME##.rfkh.h
[Info] Output directory: /home/exuvo/code/Aurora-C/src/refureku
[Info] Parsed directories:
[Info] Ignored directories:
[Info] 	/home/exuvo/code/Aurora-C/src/refureku
[Info] Project include directories:
[Info] 	/home/exuvo/code/Aurora-C/lib/tracy/common
[Info] 	/home/exuvo/code/Aurora-C/lib/tracy/client
[Info] 	/home/exuvo/code/Aurora-C/lib/imgui_sugar
[Info] 	/usr/include/apr-1
[Info] 	/home/exuvo/code/Aurora-C/lib/Refureku/Refureku/Library/Include/Public
[Info] 	/home/exuvo/code/Aurora-C/src
[Info] 	/home/exuvo/code/Aurora-C/lib/asmlib
[Info] 	/home/exuvo/code/Aurora-C/lib/tlsf
[Info] 	/home/exuvo/code/Aurora-C/lib/tracy
[Info] 	/home/exuvo/code/Aurora-C/lib/soloud/include
[Info] 	/home/exuvo/code/Aurora-C/lib/stb
[Info] 	/home/exuvo/code/Aurora-C/lib/SLikeNet/Source/include
[Info] 	/home/exuvo/code/Aurora-C/lib/mimalloc/include
[Info] 	/usr/include/freetype2
[Info] 	/home/exuvo/code/Aurora-C/lib/entt/src
[Info] 	/usr/include
[Info] Start parsing: /home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp
[Info] /home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp: Found 0 namespace(s), 5 struct(s), 0 classe(s) and 0 enum(s).
[Info] Start parsing: /home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp
[Info] /home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp: Found 0 namespace(s), 5 struct(s), 0 classe(s) and 0 enum(s).
[Info] (Re)generated metadata for 2 file(s) in 1.636000 seconds.
[Info] Metadata of 15 file(s) up-to-date.
```

**Comment by exuvo** [comment]
Okay i think this has actually been a problem for longer but i have just not modified those files in a very long while as i have been working on other parts and my generated folder is outside the build directory so it does not get reset with clean builds. I got another file to fail with the same problem if i added a space to it forcing a regeneration.

The triggering change i did to the up above file was to add a TODO comment.

**Comment by jsoysouvanh** [comment]
Hi,

Okay that's super weird, indeed.
I do not have a computer to look into it right now but off the top of my head the only 2 possible reasons are:
- from the beginning FILENAME uses the full path and is internally parsed to only retrieve the filename, but fails to do so for some reasons (a bug in the parsing on my side ?)
- the used libclang dynamic library version changed and the returned value for the same function call changed, hence breaking the internal calls. Can you check that the library kodgen uses is indeed the one I shipped with the repo, or has the same version?

**Comment by jsoysouvanh** [comment]
Ok, I've had an eye to your log file again, I noticed this log `[Info] [TOML] Load class footer macro pattern: ##FILENAME##.rfkh.h`
This is the pattern that defines how your strucs/classes macros should be generated.
The ##FILENAME## tag can only be used in for headerFileName and sourceFileName patterns, you probably want to use `"##CLASSFULLNAME##_GENERATED"` here.
This should fix the strucs/classes macro problem generating full paths like `__home_exuvo_code_Aurora_C_src_starsystems_components_TimedComponents_hpp_TimedValue_GENERATED`, but I don't see how it would have any effect on the `template <>  rfk::Archetype const* rfk::getArchetype<::/home/exuvo/code/Aurora-C/src/starsystems/components/TimedComponents.hpp::TimedValue>() noexcept;\` thing.
Let me know how it turns out when you've fixed the first issue.

**Comment by jsoysouvanh** [comment]
By the way, you have a similar issue with this log `[Info] [TOML] Load header file footer macro pattern: ##FILENAME##.rfkh.h`.
This is the pattern that defines how to generate the macro name to put at the very of each header file. It's not a file name, and you want it to be different from all other generated macros. The default value put in the library is `"File_##FILENAME##_GENERATED"`, and you probably want to stick to it (or have a similar, unique pattern).

**Comment by exuvo** [comment]
okay that is weird i actually already have
```
[CodeGenUnitSettings]
# Generated files will be located here
outputDirectory = "/home/exuvo/code/Aurora-C/src/refureku"

generatedHeaderFileNamePattern = "##FILENAME##.rfkh.h"
generatedSourceFileNamePattern = "##FILENAME##.rfks.h"
classFooterMacroPattern = "##CLASSFULLNAME##_GENERATED"
headerFileFooterMacroPattern = "File_##FILENAME##_GENERATED"
```

You log the wrong thing `logger->log("[TOML] Load class footer macro pattern: " + _generatedHeaderFileNamePattern);`
Same bug in loadFileNamePatterns, loadClassFooterMacroPattern in kodgen MacroCodeGenUnitSettings.cpp

**Comment by exuvo** [comment]
I hope you don't read these on email, i make so much edits in the first minute.

**Comment by exuvo** [comment]
>     * the used libclang dynamic library version changed and the returned value for the same function call changed, hence breaking the internal calls. Can you check that the library kodgen uses is indeed the one I shipped with the repo, or has the same version?


This might be it, i have mine symlinked to the local version 15.0.7-2 which is probably newer as the included one fails to load as i do not have the older versions of dependent libraries it wants. Oh yes you shipped a 12.x version.

**Comment by exuvo** [comment]
Clang 14 (with libclang.so.13) is the oldest i can easily install and that gives the same full path problem. I'll see if i can build a 12.x version locally that loads.

**Comment by jsoysouvanh** [comment]
Let me know how it goes with libclang.12. If the problem is related to the libclang version, I might have to make a special implementation for libclang 13+ versions. Even if you use your own version of libclang, do you actually correctly use the headers shipped with this version as well?

**Comment by exuvo** [comment]
Building clang 12 right now but no i did not see that you had clang headers in there too. So i have been using your shipped clang headers with my newer clang.so .

**Comment by exuvo** [comment]
Using the correct headers works with clang 14 and clang15!
I'll cancel my build of clang 12 then.
clang-c/Index.h has gone up a minor version between clang 12 and 15 it seems.
Thanks for your help on solving this!
