### ISSUE TITLE
Issue with Obtaining Archetype and Reflection Information from std::vector<int> Field in CLASS A

### ISSUE THREAD

**Issue by basstal** [jsoysouvanh/Refureku#17]
Hello everyone,

compilation backend:  MSVC （Visual Studio 2022 community）

I'm currently encountering a challenge with our project, specifically related to reflection and archetype retrieval from a field within a class. The class in question, class CLASS() A, has a field named b, which is marked using FIELD() and is of type std::vector<int>.

Despite the field being successfully marked, I'm unable to retrieve the archetype of field b through class A's foreachfield method. Furthermore, obtaining any reflection information about this field has also proven to be impossible.

Here is a simplified overview of the issue:

Class Definition:

class A has a field b, defined as std::vector<int> and marked with FIELD().

Problem Encountered:

Unable to access the archetype of field b using foreachfield in archetype A.
No reflection information about field b can be retrieved.
I suspect the issue might be related to how std::vector<int> fields are treated in the context of our reflection system, but I'm unsure about the exact cause or how to resolve it.

Request for Assistance:

I'm looking for guidance or solutions from anyone who has faced similar challenges or has expertise in C++ reflection, especially in handling standard container types like std::vector<int>. Any insights, code snippets, or references to documentation would be greatly appreciated.

Thank you in advance for your help!

**Comment by jsoysouvanh** [comment]
Hi.

Reflection is only possible for fields that are either fundamental types, or structs / classes that are themselves reflected.
All standard library or external library types are not reflected, hence can will not be recognized by the reflection system as is.

It is partially possible to reflect such classes by using manual registration, that is described in the "Manual reflection" sub-sections [of the Wiki](https://github.com/jsoysouvanh/Refureku/wiki).

For the specific case of class templates, it is unfortunately not possible to use raw standard containers, which means that you will never be able to reflect a std::vector<AnyType> field. However, by using an intermediate class you can use all features of standard containers and add the reflection layer, [as described in this section of the Wiki](https://github.com/jsoysouvanh/Refureku/wiki/Struct-Class-template-manual-reflection).

Hope it helps.

**Comment by basstal** [comment]
thanks, I will try to add the reflection layer
